<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bandeja [
  <!ELEMENT bandeja (correo*)>
  <!ELEMENT correo (destinatarios, asunto, cuerpo, adjuntos)>
  <!ELEMENT destinatarios (para*, cc*, cco*)*>
  <!ELEMENT para (#PCDATA)>
  <!ELEMENT cc (#PCDATA)>
  <!ELEMENT cco (#PCDATA)>
  <!ELEMENT asunto (#PCDATA)>
  <!ELEMENT cuerpo (#PCDATA)>
  <!ELEMENT adjuntos (adjunto*)>
  <!ELEMENT adjunto (nombre, mime-type, longitud)>
  <!ELEMENT nombre (#PCDATA)>
  <!ELEMENT mime-type (#PCDATA)>
  <!ELEMENT longitud (#PCDATA)>
]>

<bandeja>
  <correo>
    <destinatarios>
      <para>a@a.com</para>
      <cc>a@a.com</cc>
      <cco>a@a.com</cco>
      <para>a@a.com</para>
    </destinatarios>
    <asunto>Asunto</asunto>
    <cuerpo>Cuerpo del mensaje</cuerpo>
    <adjuntos>
      <adjunto>
        <nombre>nombre de adjunto</nombre>
        <mime-type>/text/txt</mime-type>
        <longitud>1521</longitud>
      </adjunto>
    </adjuntos>
  </correo>
</bandeja>